services:
  citytourcabs:
    build:
      context: .
    image: citytourcabs:latest
    container_name: citytourcabs
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    networks:
      - dokploy-network
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dokploy-network"
      - "traefik.http.routers.citytourcabs-http.entrypoints=web"
      - "traefik.http.routers.citytourcabs-http.rule=Host(`cabs.kishorlab.dev`) || Host(`citytourcabs.in`) || Host(`www.citytourcabs.in`)"
      - "traefik.http.routers.citytourcabs-http.service=citytourcabs-svc"
      - "traefik.http.routers.citytourcabs-http.middlewares=redirect-to-https@file"
      - "traefik.http.routers.citytourcabs-https.entrypoints=websecure"
      - "traefik.http.routers.citytourcabs-https.rule=Host(`cabs.kishorlab.dev`) || Host(`citytourcabs.in`) || Host(`www.citytourcabs.in`)"
      - "traefik.http.routers.citytourcabs-https.service=citytourcabs-svc"
      - "traefik.http.routers.citytourcabs-https.tls=true"
      - "traefik.http.routers.citytourcabs-https.tls.certresolver=letsencrypt"
      - "traefik.http.services.citytourcabs-svc.loadbalancer.server.port=80"

networks:
  dokploy-network:
    external: true
  coolify:
    external: true
